---
- name: Ensure system dependencies
  ansible.builtin.package:
    name:
      - git
      - "python@3.10"
      - "openjdk@17"
      - maven
      - gcc

- name: Creating a symlink
  ansible.builtin.file:
    src: "/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk"
    dest: "/Library/Java/JavaVirtualMachines/openjdk-17.jdk"
    state: link
  become: true

- shell: /usr/libexec/java_home
  register: java_home

- name: set global envvars
  ansible.builtin.lineinfile:
    path: "~/.zprofile"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}" 
  loop:
    - regexp: '^JAVA_HOME'
      line: "JAVA_HOME={{java_home.stdout_lines[0]}}"
    - regexp: '^RULES_ENGINE'
      line: RULES_ENGINE=drools
    - regexp: '^CPPFLAGS'
      line: CPPFLAGS="-I/opt/homebrew/opt/openjdk@17/include"

- name: Upgrade pip
  ansible.builtin.pip:
    name:
      - pip
    state: latest

- name: Install pip dependencies
  ansible.builtin.pip:
    name:
      - ansible
      - ansible-runner
      - wheel
    state: latest

- name: install ansible-rulebook
  environment:
    PIP_NO_BINARY: jpy
    JAVA_HOME: "{{ java_home.stdout_lines[0] }}"
  ansible.builtin.pip:
    name: "git+https://{{ github_token }}@github.com/ansible/ansible-rulebook.git"
    state: forcereinstall

- name: install collections
  command: ansible-galaxy collection install community.general ansible.eda 

    